##
# Services
##
services:


    # AddToQueue
    con4gis_queue.onAddToQueueListenerQuery:
        class: con4gis\Queue\Classes\Listener\AddToQueueListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.addtoqueue, method: onAddToQueueListenerQuery }
        arguments:
#            - '@doctrine.orm.default_entity_manager'

    con4gis_queue.onAddToQueueListenerRun:
        class: con4gis\Queue\Classes\Listener\AddToQueueListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.addtoqueue, method: onAddToQueueListenerRun }
        arguments:
#            - '@doctrine.orm.default_entity_manager'


    # LoadQueue
    con4gis_queue.onLoadQueueListenerQuery:
        class: con4gis\Queue\Classes\Listener\LoadQueueListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.loadqueue, method: onLoadQueueListenerQuery }
        arguments:
#            - '@doctrine.orm.default_entity_manager'

    con4gis_queue.onLoadQueueListenerRun:
        class: con4gis\Queue\Classes\Listener\LoadQueueListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.loadqueue, method: onLoadQueueListenerRun }
        arguments:
#            - '@doctrine.orm.default_entity_manager'


    # SetStartTime
    con4gis_queue.onSetStartTimeListenerQuery:
        class: con4gis\Queue\Classes\Listener\QueueSetStartTimeListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.setstarttime, method: onSetStartTimeListenerQuery }
        arguments:
#            - '@doctrine.orm.default_entity_manager'

    con4gis_queue.onSetStartTimeListenerRun:
        class: con4gis\Queue\Classes\Listener\QueueSetStartTimeListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.setstarttime, method: onSetStartTimeListenerRun }
        arguments:
#            - '@doctrine.orm.default_entity_manager'


    # SetEndTime
    con4gis_queue.onSetEndTimeListenerQuery:
        class: con4gis\Queue\Classes\Listener\QueueSetEndTimeListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.setendtime, method: onSetEndTimeListenerQuery }
        arguments:
#            - '@doctrine.orm.default_entity_manager'

    con4gis_queue.onSetEndTimeListenerRun:
        class: con4gis\Queue\Classes\Listener\QueueSetEndTimeListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.setendtime, method: onSetEndTimeListenerRun }
        arguments:
#            - '@doctrine.orm.default_entity_manager'
