##
# Services
##
services:


    # AddToQueue
    con4gis_queue.onAddToQueueListenerLoadOldData:
        class: con4gis\QueueBundle\Classes\Listener\AddToQueueListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.addtoqueue, method: onAddToQueueListenerLoadOldData }

    con4gis_queue.onAddToQueueListenerQueryKind:
        class: con4gis\QueueBundle\Classes\Listener\AddToQueueListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.addtoqueue, method: onAddToQueueListenerQueryKind }

    con4gis_queue.onAddToQueueListenerQuery:
        class: con4gis\QueueBundle\Classes\Listener\AddToQueueListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.addtoqueue, method: onAddToQueueListenerQuery }

    con4gis_queue.onAddToQueueListenerQueryWhere:
        class: con4gis\QueueBundle\Classes\Listener\AddToQueueListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.addtoqueue, method: onAddToQueueListenerQueryWhere }

    con4gis_queue.onAddToQueueListenerRun:
        class: con4gis\QueueBundle\Classes\Listener\AddToQueueListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.addtoqueue, method: onAddToQueueListenerRun }


    # LoadQueue
    con4gis_queue.onLoadQueueListenerQuery:
        class: con4gis\QueueBundle\Classes\Listener\LoadQueueListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.loadqueue, method: onLoadQueueListenerQuery }

    con4gis_queue.onLoadQueueListenerRun:
        class: con4gis\QueueBundle\Classes\Listener\LoadQueueListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.loadqueue, method: onLoadQueueListenerRun }


    # SetStartTime
    con4gis_queue.onSetStartTimeListenerQuery:
        class: con4gis\QueueBundle\Classes\Listener\QueueSetStartTimeListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.setstarttime, method: onSetStartTimeListenerQuery }

    con4gis_queue.onSetStartTimeListenerRun:
        class: con4gis\QueueBundle\Classes\Listener\QueueSetStartTimeListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.setstarttime, method: onSetStartTimeListenerRun }


    # SetEndTime
    con4gis_queue.onSetEndTimeListenerQuery:
        class: con4gis\QueueBundle\Classes\Listener\QueueSetEndTimeListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.setendtime, method: onSetEndTimeListenerQuery }

    con4gis_queue.onSetEndTimeListenerRun:
        class: con4gis\QueueBundle\Classes\Listener\QueueSetEndTimeListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.setendtime, method: onSetEndTimeListenerRun }


    # SetError
    con4gis_queue.onSetErrorListenerQuery:
        class: con4gis\QueueBundle\Classes\Listener\QueueSetErrorListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.seterror, method: onSetErrorListenerQuery }

    con4gis_queue.onSetErrorListenerRun:
        class: con4gis\QueueBundle\Classes\Listener\QueueSetErrorListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.seterror, method: onSetErrorListenerRun }


    # SetError
    con4gis_queue.onSaveJobResultQuery:
        class: con4gis\QueueBundle\Classes\Listener\QueueSaveJobResultListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.savejobresult, method: onSaveJobResultQuery }

    con4gis_queue.onSaveJobResultRun:
        class: con4gis\QueueBundle\Classes\Listener\QueueSaveJobResultListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.savejobresult, method: onSaveJobResultRun }


    # Response
    con4gis_queue.onQueueResponseListenerRun:
        class: con4gis\QueueBundle\Classes\Listener\QueueResponseListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.response, method: onQueueResponseListenerLoadContent }

    con4gis_queue.onQueueResponseListenerGenerate:
        class: con4gis\QueueBundle\Classes\Listener\QueueResponseListener
        tags:
            - { name: kernel.event_listener, event: con4gis.queue.response, method: onQueueResponseListenerGenerate }